users:
  super:
    first_name: Super
    last_name: Admin
    password: super
    portals:
      - NUCATSassist:
  admin:
    first_name: Jane
    last_name: Admin
    password: admin
    portals:
      - NUCATSassist:
  user:
    first_name: Joe
    last_name: User
    password: user
    portals:
      - NUCATSassist:
