<%
  require 'bcdatabase'
  bcdb = Bcdatabase.load
%>

<%= bcdb.development :local_postgresql, :nucats_assist %>
<%= bcdb.test :local_postgresql, :nucats_assist_test %>
<%= bcdb.staging :pstage, :nucats_assist %>
<%= bcdb.production :pprod, :nucats_assist %>
